#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# emm3
#
# Copyright (C) 2016 Christopher Halbersma (chalbersma.12@gmail.com)
# Copyright (C) 2006 Florian Schmidt (flo@fastflo.de)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

from tkinter import *
from emmalib import emmerGUI


root = Tk()

app = emmerGUI.emmerGUI(root)

root.title("Emmer")
root.mainloop()
